# need to set up in gitlab ci variables: 
# @ GIT_REPO
# @ DEPLOY_AWS_PRIVATE_KEY
# @ DEPLOY_GIT_PRIVATE_KEY
# @ DEV_INSTANCE_IP
# @ PROD_INSTANCE_IP

image: docker:19.03.1

services:
  - docker:19.03.1-dind

stages:
  - test
  - dev-test-build
  - dev-deploy
  - prod-test-build
  - prod-deploy

test:
  image: sonnguyeninslife/alekzonde-docker-puppeteer-fork
  stage: test
  variables:
    GIT_STRATEGY: fetch
    NODE_ENV: development
    IS_BUILD: "true"
  script:
    - . ops/git_init.sh
    - npm install
    - npm run tslint
    - npm run sasslint
    - npm run build
    - npm run start:staging --silent &
    - . ops/wait_apis.sh
    - npm run test -- -u
    - . ops/git_push_build.sh
  except: 
    refs:
      - master
      - dev
    variables:
      - $CI_COMMIT_MESSAGE =~ /upload latest screenshots/
      - $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_BRANCH == "dev" 

dev-test-build:
  stage: dev-test-build
  variables:
    GIT_STRATEGY: fetch
    NODE_ENV: development
    IS_BUILD: "true"
    BRANCH: dev
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY/coreproducts/web-apps/company-web
  script:
    - . ops/nodejs_install.sh
    - npm install
    - npm run tslint
    - npm run build
    - docker build -t $CI_REGISTRY/coreproducts/web-apps/company-web .
    - docker run --name company-web -d -p 3005:3005 -e NODE_ENV=staging $CI_REGISTRY/coreproducts/web-apps/company-web
    - . ops/wait_apis.sh
    - docker push $CI_REGISTRY/coreproducts/web-apps/company-web
  after_script:
    - (docker rm `docker ps -a | grep Exited | awk '{ print $1 }'`) || true
    - (docker rmi `docker images | grep "<none>" | awk '{ print $3 }'` &> /dev/null) || true
  only:
    - master

dev-deploy:
  stage: dev-deploy
  variables:
    NODE_ENV: development
  script:
    - . ops/key_setup.sh
    - ssh ec2-user@$DEV_INSTANCE_IP -i ~/.ssh/ec2-cc.pem -o StrictHostKeyChecking=no "docker stop company-web || true && docker rm company-web || true"
    - ssh ec2-user@$DEV_INSTANCE_IP -i ~/.ssh/ec2-cc.pem -o StrictHostKeyChecking=no "docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY/coreproducts/web-apps/company-web"
    - ssh ec2-user@$DEV_INSTANCE_IP -i ~/.ssh/ec2-cc.pem -o StrictHostKeyChecking=no "docker pull $CI_REGISTRY/coreproducts/web-apps/company-web"
    - ssh ec2-user@$DEV_INSTANCE_IP -i ~/.ssh/ec2-cc.pem -o StrictHostKeyChecking=no "docker run --restart always --name company-web -d -p 3005:3005 -e NODE_ENV=production $CI_REGISTRY/coreproducts/web-apps/company-web"
    - ssh ec2-user@$DEV_INSTANCE_IP -i ~/.ssh/ec2-cc.pem -o StrictHostKeyChecking=no "(docker rmi `docker images | grep "<none>" | awk '{ print $3 }'` &> /dev/null) || true"
  only:
    - master

# prod-test-build:
#   stage: prod-test-build
#   variables:
#     GIT_STRATEGY: fetch
#     NODE_ENV: production
#     IS_BUILD: "true"
#     BRANCH: dev
#   script:
#     - . ops/nodejs_install.sh
#     - npm install
#     - npm run lint
#     - npm run build
#     - npm run test:e2e
#     - npm run test
#     - docker build -t $CI_REGISTRY/coreproducts/apis/service-one-prod .
#     - docker push $CI_REGISTRY/coreproducts/apis/service-one-prod
#   only:
#     - tags

# prod-deploy:
#   stage: prod-deploy
#   variables:
#     NODE_ENV: production
#   script:
#     - . ops/key_setup.sh
#     - ssh ec2-user@13.59.157.214 -i ~/.ssh/ec2-cc.pem -o StrictHostKeyChecking=no "docker stop service-one-prod || true && docker rm service-one-prod || true && docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY/coreproducts/apis/service-one-prod && docker pull $CI_REGISTRY/coreproducts/apis/service-one-prod && docker run --restart always --name service-one-prod -d -p 3000:3000 -e NODE_ENV=production $CI_REGISTRY/coreproducts/apis/service-one-prod && (docker rmi `docker images | grep "<none>" | awk '{ print $3 }'` &> /dev/null) || true"
#   only:
#     - tags
